// 99 Names of Allah (Asma ul Husna)
export const ALLAH_NAMES = [
    { number: 1, arabic: "ٱلْرَّحْمَـانُ", transliteration: "Ar-Rahman", meaning: "The Most Compassionate", reflection: "His mercy encompasses all creation." },
    { number: 2, arabic: "ٱلْرَّحِيْمُ", transliteration: "Ar-Raheem", meaning: "The Most Merciful", reflection: "Special mercy for believers." },
    { number: 3, arabic: "ٱلْمَلِكُ", transliteration: "Al-Malik", meaning: "The King", reflection: "Sovereign Lord of all." },
    { number: 4, arabic: "ٱلْقُدُّوسُ", transliteration: "Al-Quddus", meaning: "The Most Sacred", reflection: "Pure from all imperfections." },
    { number: 5, arabic: "ٱلْسَّلَامُ", transliteration: "As-Salam", meaning: "The Peace", reflection: "Source of all peace." },
    { number: 6, arabic: "ٱلْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning: "Guardian of Faith", reflection: "Grants security to hearts." },
    { number: 7, arabic: "ٱلْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning: "The Protector", reflection: "The Watchful Guardian." },
    { number: 8, arabic: "ٱلْعَزِيزُ", transliteration: "Al-Aziz", meaning: "The Almighty", reflection: "Invincible and Honorable." },
    { number: 9, arabic: "ٱلْجَبَّارُ", transliteration: "Al-Jabbar", meaning: "The Compeller", reflection: "Mends what is broken." },
    { number: 10, arabic: "ٱلْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: "The Supreme", reflection: "Possessing all greatness." },
    { number: 11, arabic: "ٱلْخَالِقُ", transliteration: "Al-Khaliq", meaning: "The Creator", reflection: "Brings all to existence." },
    { number: 12, arabic: "ٱلْبَارِئُ", transliteration: "Al-Bari", meaning: "The Originator", reflection: "Creator in perfect proportion." },
    { number: 13, arabic: "ٱلْمُصَوِّرُ", transliteration: "Al-Musawwir", meaning: "The Fashioner", reflection: "Shapes all creation." },
    { number: 14, arabic: "ٱلْغَفَّارُ", transliteration: "Al-Ghaffar", meaning: "Repeatedly Forgiving", reflection: "Forgives again and again." },
    { number: 15, arabic: "ٱلْقَهَّارُ", transliteration: "Al-Qahhar", meaning: "The Subduer", reflection: "Dominant over all." },
    { number: 16, arabic: "ٱلْوَهَّابُ", transliteration: "Al-Wahhab", meaning: "The Bestower", reflection: "Gives freely." },
    { number: 17, arabic: "ٱلْرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning: "The Provider", reflection: "Sustainer of all." },
    { number: 18, arabic: "ٱلْفَتَّاحُ", transliteration: "Al-Fattah", meaning: "The Opener", reflection: "Opens all doors." },
    { number: 19, arabic: "ٱلْعَلِيمُ", transliteration: "Al-'Aleem", meaning: "The All-Knowing", reflection: "Knowledge is infinite." },
    { number: 20, arabic: "ٱلْقَابِضُ", transliteration: "Al-Qabid", meaning: "The Constrictor", reflection: "Restricts as He wills." },
    { number: 21, arabic: "ٱلْبَاسِطُ", transliteration: "Al-Basit", meaning: "The Extender", reflection: "Grants abundance." },
    { number: 22, arabic: "ٱلْخَافِضُ", transliteration: "Al-Khafid", meaning: "The Reducer", reflection: "Humbles whom He wills." },
    { number: 23, arabic: "ٱلْرَّافِعُ", transliteration: "Ar-Rafi'", meaning: "The Exalter", reflection: "Elevates in rank." },
    { number: 24, arabic: "ٱلْمُعِزُّ", transliteration: "Al-Mu'izz", meaning: "The Honorer", reflection: "Gives honor." },
    { number: 25, arabic: "ٱلْمُذِلُّ", transliteration: "Al-Mudhill", meaning: "The Humiliator", reflection: "Humiliates the arrogant." },
    { number: 26, arabic: "ٱلْسَّمِيعُ", transliteration: "As-Sami'", meaning: "The All-Hearing", reflection: "Hears everything." },
    { number: 27, arabic: "ٱلْبَصِيرُ", transliteration: "Al-Baseer", meaning: "The All-Seeing", reflection: "Sees all, visible and hidden." },
    { number: 28, arabic: "ٱلْحَكَمُ", transliteration: "Al-Hakam", meaning: "The Judge", reflection: "Judges with perfect justice." },
    { number: 29, arabic: "ٱلْعَدْلُ", transliteration: "Al-'Adl", meaning: "The Just", reflection: "Perfectly fair." },
    { number: 30, arabic: "ٱللَّطِيفُ", transliteration: "Al-Lateef", meaning: "The Subtle", reflection: "The Most Gentle." },
    { number: 31, arabic: "ٱلْخَبِيرُ", transliteration: "Al-Khabeer", meaning: "The All-Aware", reflection: "Knows all details." },
    { number: 32, arabic: "ٱلْحَلِيمُ", transliteration: "Al-Haleem", meaning: "The Forbearing", reflection: "Patient with us." },
    { number: 33, arabic: "ٱلْعَظِيمُ", transliteration: "Al-'Azeem", meaning: "The Magnificent", reflection: "Greatness beyond comprehension." },
    { number: 34, arabic: "ٱلْغَفُورُ", transliteration: "Al-Ghafoor", meaning: "The Forgiving", reflection: "Covers our sins." },
    { number: 35, arabic: "ٱلْشَّكُورُ", transliteration: "Ash-Shakoor", meaning: "The Appreciative", reflection: "Rewards small deeds." },
    { number: 36, arabic: "ٱلْعَلِيُّ", transliteration: "Al-'Aliyy", meaning: "The Most High", reflection: "Above everything." },
    { number: 37, arabic: "ٱلْكَبِيرُ", transliteration: "Al-Kabeer", meaning: "The Most Great", reflection: "Greater than all." },
    { number: 38, arabic: "ٱلْحَفِيظُ", transliteration: "Al-Hafeez", meaning: "The Preserver", reflection: "Protects all." },
    { number: 39, arabic: "ٱلْمُقِيتُ", transliteration: "Al-Muqeet", meaning: "The Sustainer", reflection: "Provides strength." },
    { number: 40, arabic: "ٱلْحَسِيبُ", transliteration: "Al-Haseeb", meaning: "The Reckoner", reflection: "Takes account." },
    { number: 41, arabic: "ٱلْجَلِيلُ", transliteration: "Al-Jaleel", meaning: "The Majestic", reflection: "Possesses majesty." },
    { number: 42, arabic: "ٱلْكَرِيمُ", transliteration: "Al-Kareem", meaning: "The Generous", reflection: "Gives without limit." },
    { number: 43, arabic: "ٱلْرَّقِيبُ", transliteration: "Ar-Raqeeb", meaning: "The Watchful", reflection: "Observes all." },
    { number: 44, arabic: "ٱلْمُجِيبُ", transliteration: "Al-Mujeeb", meaning: "The Responsive", reflection: "Answers prayers." },
    { number: 45, arabic: "ٱلْوَاسِعُ", transliteration: "Al-Wasi'", meaning: "All-Encompassing", reflection: "Vastness is limitless." },
    { number: 46, arabic: "ٱلْحَكِيمُ", transliteration: "Al-Hakeem", meaning: "The Wise", reflection: "Perfectly wise." },
    { number: 47, arabic: "ٱلْوَدُودُ", transliteration: "Al-Wadud", meaning: "The Loving", reflection: "Loves His servants." },
    { number: 48, arabic: "ٱلْمَجِيدُ", transliteration: "Al-Majeed", meaning: "The Glorious", reflection: "Glorious and noble." },
    { number: 49, arabic: "ٱلْبَاعِثُ", transliteration: "Al-Ba'ith", meaning: "The Resurrector", reflection: "Resurrects all." },
    { number: 50, arabic: "ٱلْشَّهِيدُ", transliteration: "Ash-Shaheed", meaning: "The Witness", reflection: "Witnesses everything." },
    { number: 51, arabic: "ٱلْحَقُّ", transliteration: "Al-Haqq", meaning: "The Truth", reflection: "The ultimate reality." },
    { number: 52, arabic: "ٱلْوَكِيلُ", transliteration: "Al-Wakeel", meaning: "The Trustee", reflection: "On whom we rely." },
    { number: 53, arabic: "ٱلْقَوِيُّ", transliteration: "Al-Qawiyy", meaning: "The Strong", reflection: "Complete strength." },
    { number: 54, arabic: "ٱلْمَتِينُ", transliteration: "Al-Mateen", meaning: "The Firm", reflection: "Eternal strength." },
    { number: 55, arabic: "ٱلْوَلِيُّ", transliteration: "Al-Waliyy", meaning: "The Protector", reflection: "Friend of believers." },
    { number: 56, arabic: "ٱلْحَمِيدُ", transliteration: "Al-Hameed", meaning: "Praiseworthy", reflection: "Deserves all praise." },
    { number: 57, arabic: "ٱلْمُحْصِيُ", transliteration: "Al-Muhsee", meaning: "The Counter", reflection: "Knows all numbers." },
    { number: 58, arabic: "ٱلْمُبْدِئُ", transliteration: "Al-Mubdi", meaning: "The Originator", reflection: "Begins all creation." },
    { number: 59, arabic: "ٱلْمُعِيدُ", transliteration: "Al-Mu'eed", meaning: "The Restorer", reflection: "Brings back." },
    { number: 60, arabic: "ٱلْمُحْيِى", transliteration: "Al-Muhyi", meaning: "Giver of Life", reflection: "Gives life to all." },
    { number: 61, arabic: "ٱلْمُمِيتُ", transliteration: "Al-Mumeet", meaning: "Taker of Life", reflection: "Causes death." },
    { number: 62, arabic: "ٱلْحَىُّ", transliteration: "Al-Hayy", meaning: "The Ever-Living", reflection: "Eternally alive." },
    { number: 63, arabic: "ٱلْقَيُّومُ", transliteration: "Al-Qayyoom", meaning: "Self-Sustaining", reflection: "Sustains all." },
    { number: 64, arabic: "ٱلْوَاجِدُ", transliteration: "Al-Wajid", meaning: "The Finder", reflection: "Finds what He wishes." },
    { number: 65, arabic: "ٱلْمَاجِدُ", transliteration: "Al-Majid", meaning: "The Noble", reflection: "Honored and generous." },
    { number: 66, arabic: "ٱلْوَاحِدُ", transliteration: "Al-Wahid", meaning: "The Unique", reflection: "Unique in essence." },
    { number: 67, arabic: "ٱلْأَحَد", transliteration: "Al-Ahad", meaning: "The One", reflection: "Indivisible in oneness." },
    { number: 68, arabic: "ٱلْصَّمَدُ", transliteration: "As-Samad", meaning: "The Eternal", reflection: "To whom all turn." },
    { number: 69, arabic: "ٱلْقَادِرُ", transliteration: "Al-Qadir", meaning: "The Capable", reflection: "Power over all." },
    { number: 70, arabic: "ٱلْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: "The Dominant", reflection: "Ultimate power." },
    { number: 71, arabic: "ٱلْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: "The Expediter", reflection: "Brings forward." },
    { number: 72, arabic: "ٱلْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer", reflection: "Delays what He wills." },
    { number: 73, arabic: "ٱلأَوَّلُ", transliteration: "Al-Awwal", meaning: "The First", reflection: "No beginning." },
    { number: 74, arabic: "ٱلْآخِرُ", transliteration: "Al-Akhir", meaning: "The Last", reflection: "No end." },
    { number: 75, arabic: "ٱلْظَّاهِرُ", transliteration: "Az-Zahir", meaning: "The Manifest", reflection: "Evident in creation." },
    { number: 76, arabic: "ٱلْبَاطِنُ", transliteration: "Al-Batin", meaning: "The Hidden", reflection: "Hidden from comprehension." },
    { number: 77, arabic: "ٱلْوَالِي", transliteration: "Al-Wali", meaning: "The Governor", reflection: "Governs all." },
    { number: 78, arabic: "ٱلْمُتَعَالِي", transliteration: "Al-Muta'ali", meaning: "The Supreme", reflection: "Exalted above all." },
    { number: 79, arabic: "ٱلْبَرُّ", transliteration: "Al-Barr", meaning: "Source of Goodness", reflection: "Who is kind." },
    { number: 80, arabic: "ٱلْتَّوَّابُ", transliteration: "At-Tawwab", meaning: "Acceptor of Repentance", reflection: "Accepts repentance." },
    { number: 81, arabic: "ٱلْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning: "The Avenger", reflection: "Punishes wrongdoing." },
    { number: 82, arabic: "ٱلْعَفُوُّ", transliteration: "Al-'Afuww", meaning: "The Pardoner", reflection: "Erases sins." },
    { number: 83, arabic: "ٱلْرَّؤُفُ", transliteration: "Ar-Ra'oof", meaning: "The Compassionate", reflection: "Deep compassion." },
    { number: 84, arabic: "مَالِكُ ٱلْمُلْكُ", transliteration: "Malik-ul-Mulk", meaning: "Owner of Sovereignty", reflection: "Absolute ownership." },
    { number: 85, arabic: "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامُ", transliteration: "Dhul-Jalali wal-Ikram", meaning: "Lord of Majesty", reflection: "Deserves glorification." },
    { number: 86, arabic: "ٱلْمُقْسِطُ", transliteration: "Al-Muqsit", meaning: "The Equitable", reflection: "Establishes justice." },
    { number: 87, arabic: "ٱلْجَامِعُ", transliteration: "Al-Jami'", meaning: "The Gatherer", reflection: "Will gather all." },
    { number: 88, arabic: "ٱلْغَنيُّ", transliteration: "Al-Ghaniyy", meaning: "Self-Sufficient", reflection: "Needs nothing." },
    { number: 89, arabic: "ٱلْمُغْنِيُ", transliteration: "Al-Mughni", meaning: "The Enricher", reflection: "Makes others wealthy." },
    { number: 90, arabic: "ٱلْمَانِعُ", transliteration: "Al-Mani'", meaning: "The Preventer", reflection: "Protects from harm." },
    { number: 91, arabic: "ٱلْضَّارُ", transliteration: "Ad-Darr", meaning: "The Distresser", reflection: "Brings necessary hardship." },
    { number: 92, arabic: "ٱلْنَّافِعُ", transliteration: "An-Nafi'", meaning: "The Benefactor", reflection: "Brings benefit." },
    { number: 93, arabic: "ٱلْنُّورُ", transliteration: "An-Nur", meaning: "The Light", reflection: "Illuminates hearts." },
    { number: 94, arabic: "ٱلْهَادِي", transliteration: "Al-Hadi", meaning: "The Guide", reflection: "Guides to right path." },
    { number: 95, arabic: "ٱلْبَدِيعُ", transliteration: "Al-Badi'", meaning: "The Incomparable", reflection: "Creates uniquely." },
    { number: 96, arabic: "ٱلْبَاقِي", transliteration: "Al-Baqi", meaning: "The Everlasting", reflection: "Remains when all perish." },
    { number: 97, arabic: "ٱلْوَارِثُ", transliteration: "Al-Warith", meaning: "The Inheritor", reflection: "Inherits all." },
    { number: 98, arabic: "ٱلْرَّشِيدُ", transliteration: "Ar-Rasheed", meaning: "The Guide", reflection: "Guides aright." },
    { number: 99, arabic: "ٱلْصَّبُورُ", transliteration: "As-Saboor", meaning: "The Patient", reflection: "Infinitely patient." }
];

// Get today's name based on day of year (rotates through all 99)
export const getTodaysName = () => {
    const start = new Date(new Date().getFullYear(), 0, 0);
    const diff = new Date() - start;
    const oneDay = 1000 * 60 * 60 * 24;
    const dayOfYear = Math.floor(diff / oneDay);
    const index = dayOfYear % ALLAH_NAMES.length;
    return ALLAH_NAMES[index];
};
